spring:
  application:
    name: yangziwang
  cloud:
    nacos:
      discovery:
        server-addr: ${yangziwang.public.ip}:${yangziwang.public.port}
        namespace: 3d21cc23-5d35-4c45-9dfc-508909a098d4
      config:
        server-addr: ${yangziwang.public.ip}:${yangziwang.public.port}
        namespace: 3d21cc23-5d35-4c45-9dfc-508909a098d4
        enabled: true
        file-extension: yaml
  config:
    import:
      - optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
server:
  port: 8082
yangziwang:
  public:
    ip: 127.0.0.1
    port: 8848